core/routes/web.php
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetCodeEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify.code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware(['admin'])->group(function () {
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');

        //Notification
        Route::get('notifications','AdminController@notifications')->name('notifications');
        Route::get('notification/read/{id}','AdminController@notificationRead')->name('notification.read');
        Route::get('notifications/read-all','AdminController@readAll')->name('notifications.readAll');

        // mlm plan
        Route::get('plans', 'MlmController@plan')->name('plan');
        Route::post('plan/store', 'MlmController@planStore')->name('plan.store');
        Route::post('plan/update', 'MlmController@planUpdate')->name('plan.update');

        Route::get('jabatan', 'JabatanController@index')->name('jabatan');
        Route::post('jabatan/store', 'JabatanController@store')->name('jabatan.store');
        Route::post('jabatan/update', 'JabatanController@update')->name('jabatan.update');

        // matching bonus
        Route::post('matching-bonus/update', 'MlmController@matchingUpdate')->name('matching-bonus.update');

        // tree
        Route::get('/tree/{id}', 'ManageUsersController@tree')->name('users.single.tree');
        Route::get('/user/tree/{user}', 'ManageUsersController@oth\erTree')->name('users.other.tree');
        Route::get('/user/tree/search', 'ManageUsersController@otherTree')->name('users.other.tree.search');

        Route::get('notice', 'GeneralSettingController@noticeIndex')->name('setting.notice');
        Route::post('notice/update', 'GeneralSettingController@noticeUpdate')->name('setting.notice.update');


        //============== start the category route ===========
        Route::name('category.')->prefix('category')->group(function () {
            Route::get('/', 'CategoryController@index')->name('index');
            Route::post('/store', 'CategoryController@store')->name('store');
            Route::post('/update/{id}', 'CategoryController@update')->name('update');
            Route::get('/status/change/{id}', 'CategoryController@changeStatus')->name('status.change');
        });

         //============== start the product route ===========
         Route::name('product.')->prefix('product')->group(function () {
            Route::get('/', 'ProductController@index')->name('index');
            Route::get('/create', 'ProductController@create')->name('create');
            Route::post('/store', 'ProductController@store')->name('store');
            Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
            Route::post('/update/{id}', 'ProductController@update')->name('update');
            Route::get('/status/change/{id}', 'ProductController@changeStatus')->name('status.change');
            Route::get('/comm/change/{id}', 'ProductController@changeComm')->name('comm.change');
            Route::get('remove-image/{id}/{key}', 'ProductController@removeImage')->name('image.remove');
        });


        //Report Bugs
        Route::get('request-report','AdminController@requestReport')->name('request.report');
        Route::post('request-report','AdminController@reportSubmit');

        Route::get('system-info','AdminController@systemInfo')->name('system.info');


        // Users Manager
        Route::get('users', 'ManageUsersController@allUsers')->name('users.all');
        Route::get('users/active', 'ManageUsersController@activeUsers')->name('users.active');
        Route::get('users/banned', 'ManageUsersController@bannedUsers')->name('users.banned');
        Route::get('users/email-verified', 'ManageUsersController@emailVerifiedUsers')->name('users.email.verified');
        Route::get('users/email-unverified', 'ManageUsersController@emailUnverifiedUsers')->name('users.email.unverified');
        Route::get('users/sms-unverified', 'ManageUsersController@smsUnverifiedUsers')->name('users.sms.unverified');
        Route::get('users/sms-verified', 'ManageUsersController@smsVerifiedUsers')->name('users.sms.verified');
        Route::get('users/with-balance', 'ManageUsersController@usersWithBalance')->name('users.with.balance');

        Route::get('users/{scope}/search', 'ManageUsersController@search')->name('users.search');
        Route::get('user/detail/{id}', 'ManageUsersController@detail')->name('users.detail');
        Route::post('user/update/{id}', 'ManageUsersController@update')->name('users.update');
        Route::post('user/add-sub-balance/{id}', 'ManageUsersController@addSubBalance')->name('users.add.sub.balance');
        Route::post('user/add-sub-ticket/{id}', 'ManageUsersController@addSubTicket')->name('users.add.sub.ticket');
        Route::get('user/send-email/{id}', 'ManageUsersController@showEmailSingleForm')->name('users.email.single');
        Route::post('user/send-email/{id}', 'ManageUsersController@sendEmailSingle')->name('users.email.single');
        Route::get('user/login/{id}', 'ManageUsersController@login')->name('users.login');
        Route::get('user/transactions/{id}', 'ManageUsersController@transactions')->name('users.transactions');
        Route::get('user/deposits/{id}', 'ManageUsersController@deposits')->name('users.deposits');
        Route::get('user/deposits/via/{method}/{type?}/{userId}', 'ManageUsersController@depositViaMethod')->name('users.deposits.method');
        Route::get('user/withdrawals/{id}', 'ManageUsersController@withdrawals')->name('users.withdrawals');
        Route::get('user/withdrawals/via/{method}/{type?}/{userId}', 'ManageUsersController@withdrawalsViaMethod')->name('users.withdrawals.method');
        Route::post('user/rek/{id}', 'ManageUsersController@rek')->name('users.rek');
        Route::post('user/updateNik/{id}', 'ManageUsersController@updateNik')->name('users.updateNik');
        Route::post('user/verify/{id}', 'ManageUsersController@verify')->name('users.verify');
        Route::post('user/reject/{id}', 'ManageUsersController@reject')->name('users.reject');
        // Login History
        Route::get('users/login/history/{id}', 'ManageUsersController@userLoginHistory')->name('users.login.history.single');

        Route::get('users/send-email', 'ManageUsersController@showEmailAllForm')->name('users.email.all');
        Route::post('users/send-email', 'ManageUsersController@sendEmailAll')->name('users.email.send');
        Route::get('users/email-log/{id}', 'ManageUsersController@emailLog')->name('users.email.log');
        Route::get('users/email-details/{id}', 'ManageUsersController@emailDetails')->name('users.email.details');

        Route::get('user/referral/{id}', 'ManageUsersController@userRef')->name('users.ref');

        // Subscriber
        Route::get('subscriber', 'SubscriberController@index')->name('subscriber.index');
        Route::get('subscriber/send-email', 'SubscriberController@sendEmailForm')->name('subscriber.sendEmail');
        Route::post('subscriber/remove', 'SubscriberController@remove')->name('subscriber.remove');
        Route::post('subscriber/send-email', 'SubscriberController@sendEmail')->name('subscriber.sendEmail');

        Route::get('gacha', 'GachamasterController@index')->name('gacha');
        Route::post('gacha/update', 'GachamasterController@update')->name('gacha.update');
        Route::get('gacha/item/{id}', 'GachamasterController@detail')->name('gacha.detail');
        Route::post('gacha/detail/update', 'GachamasterdetailController@update')->name('gacha.update.detail');
        Route::post('gacha/detail/store', 'GachamasterdetailController@add')->name('gacha.add.detail');
        Route::post('gacha/status/{id}', 'GachamasterController@status')->name('gacha.status');
        
        Route::get('gacha/plot/detail/{id}', 'GachamasterController@plot')->name('gacha.user.plot');
        Route::post('gacha/plot/detail', 'GachamasterController@addplotuser')->name('gacha.user.plot.add');



        // Deposit Gateway
        Route::name('gateway.')->prefix('gateway')->group(function(){
            // Automatic Gateway
            Route::get('automatic', 'GatewayController@index')->name('automatic.index');
            Route::get('automatic/edit/{alias}', 'GatewayController@edit')->name('automatic.edit');
            Route::post('automatic/update/{code}', 'GatewayController@update')->name('automatic.update');
            Route::post('automatic/remove/{code}', 'GatewayController@remove')->name('automatic.remove');
            Route::post('automatic/activate', 'GatewayController@activate')->name('automatic.activate');
            Route::post('automatic/deactivate', 'GatewayController@deactivate')->name('automatic.deactivate');


            // Manual Methods
            Route::get('manual', 'ManualGatewayController@index')->name('manual.index');

core/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $guarded=['id'];

    protected $casts=[
        'images'            => 'array',
        'specifications'    => 'array',
        'meta_keyword'      => 'array',
    ];

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function scopeHasCategory(){
        return $this->whereHas('category',function($q){
            $q->where('status',1);
        });
    }
}

core/resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')

@section('panel')

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body p-0">
                <div class="table-responsive--md table-responsive">
                    <table class="table table--light style--two">
                        <thead>
                            <tr>
                                <th scope="col">@lang('#')</th>
                                <th scope="col">@lang('Name')</th>
                                <th scope="col">@lang('Thumbnail')</th>
                                <th scope="col">@lang('Price')</th>
                                <th scope="col">@lang('Public Price')</th>
                                <th scope="col">@lang('SP Poin')</th>
                                <th scope="col">@lang('Quantity')</th>
                                <th scope="col">@lang('Sales Commission')</th>
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse(@$products as $key => $product)
                            <tr>
                                <td data-label="@lang('#')">{{ $products->firstItem() + $loop->index }}</td>
                                <td data-label="@lang('Name')">{{ __($product->name) }}</td>
                                <td data-label="@lang('Thumbnail')"> <img
                                        src="{{ getImage(imagePath()['products']['path'].'/'.$product->thumbnail,imagePath()['products']['size'])}}"
                                        alt="" class="shadow rounded __img"></td>
                                <td data-label="@lang('Price')">{{ __(nb($product->price)) }} {{ $general->cur_text }}
                                </td>
                                <td data-label="@lang('Public Price')">{{ __(nb($product->price_public)) }} {{
                                    $general->cur_text }}</td>
                                <td data-label="@lang('SP Poin')">{{$product->sp_poin }}</td>
                                <td data-label="@lang('Quantity')">{{ __($product->quantity) }}</td>
                                <td data-label="@lang('Sales Commission')">
                                    <div class="__comm_switch"
                                        data-action="{{ route('admin.product.comm.change', $product->id) }}"
                                        data-comm="{{ $product->is_multilevel }}" data-id="{{ $product->id }}">
                                    </div>
                                </td>
                                <td data-label="@lang('Status')">
                                    <div class="__status_switch"
                                        data-action="{{ route('admin.product.status.change', $product->id) }}"
                                        data-status="{{ $product->status }}" data-id="{{ $product->id }}">
                                    </div>
                                </td>
                                <td data-label="@lang('Action')">
                                    <a class="icon-btn edit text-white"
                                        href="{{ route('admin.product.edit',$product->id) }}" data-toggle="tooltip"
                                        data-original-title="Edit">
                                        <i class="la la-pencil"></i>
                                    </a>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td class="text-muted text-center" colspan="100%">{{ __($emptyMessage) }}</td>
                            </tr>
                            @endforelse

                        </tbody>
                    </table><!-- table end -->
                </div>
            </div>
            <div class="card-footer py-4">
                {{ @$products->links('admin.partials.paginate') }}
            </div>
        </div>
    </div>
</div>

@endsection



@push('breadcrumb-plugins')
<a href="{{ route('admin.product.create') }}" class="btn btn-sm btn--primary box--shadow1 text--small"><i
        class="las la-plus"></i>@lang('Add
    New')</a>

@endpush

@push('script')
<script>
    "use strict";
    (function($) {



    })(jQuery);

</script>

<script src="{{ asset('assets/admin/js/status-switch.js') }}"></script>
<script src="{{ asset('assets/admin/js/comm-switch.js') }}"></script>


@endpush

@push('style')
<style>
    .__img {
        max-width: 150px;
        border-radius: 5px;
        padding: 5px;
    }
</style>
@endpush