core/routes/web.php
        // Logo-Icon
        Route::get('setting/logo-icon', 'GeneralSettingController@logoIcon')->name('setting.logo.icon');
        Route::post('setting/logo-icon', 'GeneralSettingController@logoIconUpdate')->name('setting.logo.icon');

        //Custom CSS
        Route::get('custom-css','GeneralSettingController@customCss')->name('setting.custom.css');
        Route::post('custom-css','GeneralSettingController@customCssSubmit');


        //Cookie
        Route::get('cookie','GeneralSettingController@cookie')->name('setting.cookie');
        Route::post('cookie','GeneralSettingController@cookieSubmit');


        // Plugin
        Route::get('extensions', 'ExtensionController@index')->name('extensions.index');
        Route::post('extensions/update/{id}', 'ExtensionController@update')->name('extensions.update');
        Route::post('extensions/activate', 'ExtensionController@activate')->name('extensions.activate');
        Route::post('extensions/deactivate', 'ExtensionController@deactivate')->name('extensions.deactivate');



        // Email Setting
        Route::get('email-template/global', 'EmailTemplateController@emailTemplate')->name('email.template.global');
        Route::post('email-template/global', 'EmailTemplateController@emailTemplateUpdate')->name('email.template.global');
        Route::get('email-template/setting', 'EmailTemplateController@emailSetting')->name('email.template.setting');
        Route::post('email-template/setting', 'EmailTemplateController@emailSettingUpdate')->name('email.template.setting');
        Route::get('email-template/index', 'EmailTemplateController@index')->name('email.template.index');
        Route::get('email-template/{id}/edit', 'EmailTemplateController@edit')->name('email.template.edit');
        Route::post('email-template/{id}/update', 'EmailTemplateController@update')->name('email.template.update');
        Route::post('email-template/send-test-mail', 'EmailTemplateController@sendTestMail')->name('email.template.test.mail');


        // SMS Setting
        Route::get('sms-template/global', 'SmsTemplateController@smsTemplate')->name('sms.template.global');
        Route::post('sms-template/global', 'SmsTemplateController@smsTemplateUpdate')->name('sms.template.global');
        Route::get('sms-template/setting','SmsTemplateController@smsSetting')->name('sms.templates.setting');
        Route::post('sms-template/setting', 'SmsTemplateController@smsSettingUpdate')->name('sms.template.setting');
        Route::get('sms-template/index', 'SmsTemplateController@index')->name('sms.template.index');
        Route::get('sms-template/edit/{id}', 'SmsTemplateController@edit')->name('sms.template.edit');
        Route::post('sms-template/update/{id}', 'SmsTemplateController@update')->name('sms.template.update');
        Route::post('email-template/send-test-sms', 'SmsTemplateController@sendTestSMS')->name('sms.template.test.sms');

        // SEO
        Route::get('seo', 'FrontendController@seoEdit')->name('seo');


        // Frontend
        Route::name('frontend.')->prefix('frontend')->group(function () {


            Route::get('templates', 'FrontendController@templates')->name('templates');
            Route::post('templates', 'FrontendController@templatesActive')->name('templates.active');


            Route::get('frontend-sections/{key}', 'FrontendController@frontendSections')->name('sections');
            Route::post('frontend-content/{key}', 'FrontendController@frontendContent')->name('sections.content');
            Route::get('frontend-element/{key}/{id?}', 'FrontendController@frontendElement')->name('sections.element');
            Route::post('remove', 'FrontendController@remove')->name('remove');

            // Page Builder
            Route::get('manage-pages', 'PageBuilderController@managePages')->name('manage.pages');
            Route::post('manage-pages', 'PageBuilderController@managePagesSave')->name('manage.pages.save');
            Route::post('manage-pages/update', 'PageBuilderController@managePagesUpdate')->name('manage.pages.update');
            Route::post('manage-pages/delete', 'PageBuilderController@managePagesDelete')->name('manage.pages.delete');
            Route::get('manage-section/{id}', 'PageBuilderController@manageSection')->name('manage.section');
            Route::post('manage-section/{id}', 'PageBuilderController@manageSectionUpdate')->name('manage.section.update');
        });
    });
});




/*
|--------------------------------------------------------------------------
| Start User Area
|--------------------------------------------------------------------------
*/


Route::name('user.')->group(function () {
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->middleware('regStatus');
    Route::post('check-mail', 'Auth\RegisterController@checkUser')->name('checkUser');

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetCodeEmail')->name('password.email');
    Route::get('password/code-verify', 'Auth\ForgotPasswordController@codeVerify')->name('password.code.verify');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/verify-code', 'Auth\ForgotPasswordController@verifyCode')->name('password.verify.code');
});

Route::name('user.')->prefix('user')->group(function () {
    Route::middleware('auth')->group(function () {
        Route::get('authorization', 'AuthorizationController@authorizeForm')->name('authorization');
        Route::get('resend-verify', 'AuthorizationController@sendVerifyCode')->name('send.verify.code');
        Route::post('verify-email', 'AuthorizationController@emailVerification')->name('verify.email');
        Route::post('verify-sms', 'AuthorizationController@smsVerification')->name('verify.sms');
        Route::post('verify-g2fa', 'AuthorizationController@g2faVerification')->name('go2fa.verify');

        Route::middleware(['checkStatus'])->group(function () {
            Route::get('dashboard', 'UserController@home')->name('home');

            Route::get('profile-setting', 'UserController@profile')->name('profile.setting');
            Route::post('profile-setting', 'UserController@submitProfile');
            Route::get('change-password', 'UserController@changePassword')->name('change.password');
            Route::post('change-password', 'UserController@submitPassword');
            Route::post('edit_rekening', 'UserController@edit_rekening')->name('edit_rekening');
            Route::post('add_rekening', 'UserController@add_rekening')->name('add_rekening');

            Route::post('add_address', 'AlamatController@add_address')->name('add_address');
            Route::post('edit_address', 'AlamatController@edit_address')->name('edit_address');
            Route::post('set_default', 'AlamatController@setDefault')->name('set_default');

            //plan
            Route::get('/plan', 'PlanController@planIndex')->name('plan.index');
            Route::post('/plan', 'PlanController@planStore')->name('plan.purchase');
            Route::get('/referral-log', 'UserController@referralCom')->name('referral.log');
            Route::get('/binary-log', 'PlanController@binaryCom')->name('binary.log');
            Route::get('/binary-summery', 'PlanController@binarySummery')->name('binary.summery');
            Route::get('/bv-log', 'PlanController@bvlog')->name('bv.log');
            Route::get('/referrals', 'PlanController@myRefLog')->name('my.ref');
            Route::get('/tree', 'PlanController@myTree')->name('my.tree');
            Route::get('/tree/{user}', 'PlanController@otherTree')->name('other.tree');
            Route::get('/tree/search', 'PlanController@otherTree')->name('other.tree.search');

            //balance transfer
            Route::get('/transfer', 'UserController@indexTransfer')->name('balance.transfer');
            Route::post('/transfer', 'UserController@balanceTransfer')->name('balance.transfer.post');
            Route::post('/search-user', 'UserController@searchUser')->name('search.user');

            //Report
            Route::get('report/deposit/log', 'UserController@depositHistory')->name('report.deposit');
            Route::get('report/invest/log', 'UserController@investLog')->name('report.invest');
            Route::get('report/transactions/log', 'UserController@transactions')->name('report.transactions');
            Route::get('report/withdraw/log', 'UserController@withdrawLog')->name('report.withdraw');
            Route::get('report/referral/commission', 'UserController@refCom')->name('report.refCom');
            Route::get('report/binary/commission', 'UserController@binaryCom')->name('report.binaryCom');


            //2FA
            Route::get('twofactor', 'UserController@show2faForm')->name('twofactor');
            Route::post('twofactor/enable', 'UserController@create2fa')->name('twofactor.enable');
            Route::post('twofactor/disable', 'UserController@disable2fa')->name('twofactor.disable');


            // Deposit
            Route::any('/deposit', 'Gateway\PaymentController@deposit')->name('deposit');
            Route::post('deposit/insert', 'Gateway\PaymentController@depositInsert')->name('deposit.insert');
            Route::get('deposit/preview', 'Gateway\PaymentController@depositPreview')->name('deposit.preview');

core/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'address' => 'object',
        'ver_code_send_at' => 'datetime'
    ];

    protected $data = [
        'data'=>1
    ];




    public function login_logs()
    {
        return $this->hasMany(UserLogin::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class)->orderBy('id','desc');
    }

    public function deposits()
    {
        return $this->hasMany(Deposit::class)->where('status','!=',0);
    }

    public function withdrawals()
    {
        return $this->hasMany(Withdrawal::class)->where('status','!=',0);
    }

    //mlm
    public function userExtra()
    {
        return $this->hasOne(UserExtra::class);
    }

    public function userBank()
    {
        return $this->hasOne(rekening::class);
    }

    public function plan()
    {
        return $this->belongsTo(Plan::class);
    }


    // SCOPES

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function scopeActive()
    {
        return $this->where('status', 1);
    }

    public function scopeBanned()
    {
        return $this->where('status', 0);
    }

    public function scopeEmailUnverified()
    {
        return $this->where('ev', 0);
    }

    public function scopeSmsUnverified()
    {
        return $this->where('sv', 0);
    }
    public function scopeEmailVerified()
    {
        return $this->where('ev', 1);
    }

    public function scopeSmsVerified()
    {
        return $this->where('sv', 1);
    }

    public function carts()
    {
        return $this->hasMany(Cart::class);
    }

    /**
     * Menghitung total jumlah barang di keranjang pengguna
     */
    // public function cartItemsCount()
    // {
    //     return $this->carts()->sum('qty');
    // }

}

core/resources/views/templates/basic/sections/about.blade.php
@php
    $aboutSectioContent = getContent($sec.'.content',true);
@endphp
@if(@$aboutSectioContent)
<!-- About Us Section Starts Here -->
<section class="about-section padding-top padding-bottom">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="about-thumb rtl">
                    <img src="{{getImage('assets/images/frontend/about/'.@$aboutSectioContent->data_values->about_image,'700x700')}}" alt="thumb"  class="w-100">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-content">
                    <div class="section-header">
                        <span class="subtitle">{{__(@$aboutSectioContent->data_values->heading)}}</span>
                        <h2 class="title">{{__(@$aboutSectioContent->data_values->sub_heading)}}</h2>
                        <p>{{__(@$aboutSectioContent->data_values->description)}}</p>
                    </div>
              
                    <a href="{{@$aboutSectioContent->data_values->button_url}}" class="cmn--btn active"><span>{{__(@$aboutSectioContent->data_values->button_text)}}</span></a>
                </div>
            </div>
        </div>
    </div>
    <div class="shape shape1"><img src="{{asset($activeTemplateTrue.'images/shape/circle-triangle.png')}}" alt="shape"></div>
    <div class="shape shape2"><img src="{{asset($activeTemplateTrue.'images/shape/circle-big.png')}}" alt="shape"></div>
</section>
<!-- About Us Section Ends Here -->

@endif

core/resources/views/templates/basic/sections/blog.blade.php
@php
    $blogSectionContent = getContent($sec.'.content',true);
    $blogs = getContent($sec.'.element',false,3);
@endphp


<!-- Blog Section Starts Here -->
<section class="blog-section padding-bottom pos-rel">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="section-header text-center">
                    <span class="subtitle">{{ __(@$blogSectionContent->data_values->heading) }}</span>
                    <h2 class="title">{{ __(@$blogSectionContent->data_values->sub_heading) }}</h2>
                </div>
            </div>
        </div>
        <div class="row justify-content-center gy-4">
            @foreach($blogs as $blog)
            <div class="col-lg-4 col-md-6 col-sm-10">
                <div class="post-item">
                    <div class="post-thumb"><img src="{{ getImage('assets/images/frontend/blog/thumb_'.$blog->data_values->blog_image) }}" alt="blog">
                        <div class="meta-date">
                            <span class="date">{{ $blog->created_at->format('d M') }}</span>
                            <span>{{ $blog->created_at->format('Y') }}</span>
                        </div>
                    </div>
                    <div class="post-content">
                        <h4 class="title"><a href="{{ route('blog.details',[slug($blog->data_values->title),$blog->id]) }}">{{ __($blog->data_values->title) }}</a></h4>
                        <p>@php echo shortDescription(strip_tags($blog->data_values->description),120) @endphp</p>
                        <a href="{{ route('blog.details',[slug($blog->data_values->title),$blog->id]) }}" class="read-more">@lang('Read More')</a>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
    <div class="shape shape1">
        <img src="{{asset($activeTemplateTrue.'images/shape/blob1.png')}}" alt="shap">
    </div>
</section>
<!-- Blog Section Ends Here -->

core/resources/views/templates/basic/sections/faq.blade.php
@php
    $faqTitle = getContent('faq.content', true);
    $faqs = getContent('faq.element');
@endphp


<section class="faq-section padding-top padding-bottom">
    <div class="container">
        <div class="section-header">
            <h2 class="title">@lang(@$faqTitle->data_values->heading)</h2>
            <p>@lang(@$faqTitle->data_values->subheading)</p>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="faq-wrapper style-two">
                    @foreach($faqs as $key => $faql)
                        <div class="faq-item">
                            <div class="faq-title">
                                <h6 class="title">{{ __(@$faql->data_values->question) }}</h6>
                                <div class="right-icon"></div>
                            </div>
                            <div class="faq-content">
                                <p>{{ __(@$faql->data_values->answer) }}</p>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>

core/resources/views/templates/basic/sections/how_it_works.blade.php
@php

$worksSectionContent = getContent($sec.'.content',true);
$worksSectionElements = getContent($sec.'.element');
@endphp
@if(@$worksSectionContent)

<!-- How it Work Section Starts Here -->
<section class="work-section padding-bottom pos-rel">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="section-header text-center">
                    <span class="subtitle">{{__(@$worksSectionContent->data_values->heading)}}</span>
                    <h2 class="title">{{__(@$worksSectionContent->data_values->sub_heading)}}</h2>
                </div>
            </div>
        </div>
        <div class="row gy-5">

            @if(@$worksSectionElements && !empty($worksSectionElements->toArray()))
            @foreach(@$worksSectionElements as $worksSectionElement)
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="work-item">
                    <div class="work-icon">@php echo @$worksSectionElement->data_values->icon @endphp</div>
                    <div class="work-content">
                        <h4 class="title">{{__(@$worksSectionElement->data_values->title)}}</h4>
                        <p>{{__(@$worksSectionElement->data_values->description)}}</p>
                    </div>
                </div>
            </div>
            @endforeach
            @endif


        </div>
    </div>
    <div class="shape shape1"><img src="{{asset($activeTemplateTrue.'images/shape/circle-big.png')}}" alt="shape"></div>
</section>
<!-- How it Work Section Ends Here -->



@endif

core/resources/views/templates/basic/sections/plan.blade.php
@php

    $planeSectionContent = getContent($sec.'.content', true);
    $plans = \App\Models\Plan::where('status', 1)->get();



@endphp



<!-- Pricing Plan Section Starts Here -->
<section class="plan-section padding-bottom pos-rel">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="section-header text-center">
                    <span class="subtitle">{{__(@$planeSectionContent->data_values->heading)}}</span>
                    <h2 class="title">{{__(@$planeSectionContent->data_values->sub_heading)}}</h2>
                </div>
            </div>
        </div>
        <div class="row justify-content-center gy-4">

            @foreach (@$plans as $k=> $plan)
             <div class="col-xl-4 col-lg-6 col-md-6 col-sm-10">
                <div class="plan-item">
                    <span class="plan-serial">{{ $k+1 }}</span>
                    <div class="plan-bottom">
                        <div class="plan-header"><div class="plan-price"><sup>{{$general->cur_sym}}</sup>{{getAmount($plan->price)}}</div></div>
                        <div class="plan-body">
                            <p class="plan-name">{{ __(@$plan->name) }}</p>
                            <ul class="plan-info">
                                <li class="active"><i  class="las la-business-time __plan_info " data="bv"></i>@lang('Business Volume: '){{ __(@$plan->bv) }}</li>
                                <li class="active"><i class="las la-comment-dollar __plan_info" data="ref_com"></i>@lang('Referral Commission: '){{$general->cur_sym}} {{getAmount($plan->ref_com)}}</li>
                                <li class="active"><i class="las la-comments-dollar __plan_info" data="tree_com"></i>@lang('Commission To Tree:') {{$general->cur_sym}} {{getAmount($plan->tree_com)}}</li>

                            </ul>
                            <div class="text-center"><a href="{{route('user.plan.index')}}"  class="cmn--btn-2 btn--md active"><span>@lang('Subscribe Plan')</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</section>

<div class="modal fade" id="__modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="__modal_title">@lang('Commission to tree info')</h5>

            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer text-right ">
               <div class="row">
                   <div class="col-lg-12">
                    <button type="button" class="btn btn-danger" id="__modal_close">@lang('Close')</button>
                   </div>
               </div>
            </div>
        </div>
    </div>
</div>

@push('script')
    <script>
        'use strict';
        (function($){
            $('.__plan_info').on('click', function (e) {
                let html="";
               let data=$(this).attr('data');
               let modal=$("#__modal");
               if(data=='bv'){
                html=` <h5>   <span class="text-danger">@lang('When someone from your below tree subscribe this plan, You will get this Business Volume  which will be used for matching bonus').</span>
                </h5>`
                modal.find('#__modal_title').html("@lang('Business Volume (BV) info')")

               }
               if(data=='ref_com'){
                 html=`  <h5>  <span class=" text-danger">@lang('When Your Direct-Referred/Sponsored  User Subscribe in') <b> @lang('ANY PLAN') </b>, @lang('You will get this amount').</span>
                        <br>
                        <br>
                        <span class="text-success"> @lang('This is the reason You should Choose a Plan With Bigger Referral Commission').</span> </h5>`
                        modal.find('#__modal_title').html("@lang('Referral Commission info')")

               }
               if(data=='tree_com'){
                    html=` <h5 class=" text-danger">@lang('When someone from your below tree subscribe this plan, You will get this amount as Tree Commission'). </h5>`
                    modal.find('#__modal_title').html(html)
                }
              modal.find('.modal-body').html(html)
               $(modal).modal('show')
             });

            $('body').on('click', '#__modal_close',function (e) {
            $("#__modal").modal('hide');
            });
        })(jQuery)
    </script>
@endpush

core/resources/views/templates/basic/sections/product.blade.php
@php
    $productSectionContent = getContent($sec.'.content', true);
    $products = App\Models\Product::where('status',1)->where('is_featured',1)->get();
@endphp

@if($productSectionContent != null)
<!-- Products Section Starts Here -->
<section class="product-section padding-bottom">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="section-header text-center">
                    <span class="subtitle">{{__(@$productSectionContent->data_values->heading)}}</span>
                    <h2 class="title">{{__(@$productSectionContent->data_values->sub_heading)}}</h2>
                </div>
            </div>
        </div>
        <div class="row gy-4">
            @foreach($products as $product)
            <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
                <div class="product-item">
                    <div class="product-thumb">
                        <img src="{{getImage(imagePath()['products']['path'].'/'.$product->thumbnail,imagePath()['products']['size'])}}" alt="products">
                        <ul class="product-options">
                            <li><a class="image" href="{{getImage(imagePath()['products']['path'].'/'.$product->thumbnail,imagePath()['products']['size'])}}"><i class="las la-expand"></i></a></li>
                        </ul>
                    </div>
                    <div class="product-content">
                        <h6 class="product-title"><a  href="{{ route('product.details',['id' => $product->id, 'slug' => slug($product->name)])}}" >{{ __(shortDescription($product->name,35)) }}</a></h6>

                        @if ($product->quantity>=0)
                        <span class="product-availablity text--success">@lang('in stock')</span>
                        @else
                        <span class="product-availablity text--danger">@lang('out stock')</span>

                        @endif


                        <div class="product-price">
                            <span class="current-price">{{ $general->cur_sym }}{{showAmount($product->price)}}</span>
                        </div>
                        <a href="{{ route('product.details',['id' => $product->id, 'slug' => slug($product->name)])}}" class="add-to-cart cmn--btn-2">@lang('Details')</a>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</section>
<!-- Products Section Ends Here -->
@endif

core/resources/views/templates/basic/sections/refer.blade.php
    @php
    $referSectionContent = getContent($sec.'.content',true);


    @endphp

    @if(@$referSectionContent)
    <!-- Referral Section Starts Here -->
    <section class="referral-section" style="background: url({{getImage('assets/images/frontend/refer//'.@$referSectionContent->data_values->background_image,'1900x1200')}}) center;">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="refer-content">

                        <h2 class="title">{{__(@$referSectionContent->data_values->heading)}}</h2>
                        <p>{{__(@$referSectionContent->data_values->description)}}</p>
                        <a href="#0" class="cmn--btn active"><span>Get Started</span></a>
                        <div class="shape shape1"><img src="{{asset($activeTemplateTrue.'images/icon/gft.png')}}" alt="icon"></div>
                    </div>
                </div>
                <div class="col-lg-6 d-none d-lg-block">
                    <div class="refer-thumb">
                        <img src="{{getImage('assets/images/frontend/refer/'.@$referSectionContent->data_values->refer_image,'650x580')}}" alt="thumb">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Referral Section Ends Here -->
    @endif

core/resources/views/templates/basic/sections/transaction.blade.php
@php
    $transactionSectionContent = getContent($sec.'.content', true);
    $transactions = App\Models\Transaction::orderBy('id','desc')->take(10)->with('user')->get();
@endphp

@if (@$transactionSectionContent)
<!-- Transection Section Starts Here -->
<section class="transection-section padding-top padding-bottom pos-rel">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="section-header text-center">
                    <span class="subtitle">{{ __(@$transactionSectionContent->data_values->heading) }}</span>
                    <h2 class="title">{{ __(@$transactionSectionContent->data_values->sub_heading) }}</h2>
                </div>
            </div>
        </div>
        <div class="transection-table-wrapper">
            <table class="transection-table">
                <thead>
                    <tr>
                        <th>@lang('User')</th>
                        <th>@lang('Trx')</th>
                        <th>@lang('Transacted')</th>
                        <th>@lang('Amount')</th>
                        <th>@lang('Post Balance')</th>
                        <th>@lang('Detail')</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($transactions as $trx)
                    <tr>
                        <td class="usr-type" data-label="@lang('User')">{{ $trx->user->fullname }}</td>
                        <td data-label="@lang('Trx')">
                            <strong>{{ $trx->trx }}</strong>
                        </td>

                        <td data-label="@lang('Transacted')">
                            {{ showDateTime($trx->created_at) }}
                        </td>

                        <td data-label="@lang('Amount')" class="budget">
                            <span class="font-weight-bold @if($trx->trx_type == '+')text-success @else text-danger @endif">
                                {{ $trx->trx_type }} {{showAmount($trx->amount)}} {{ $general->cur_text }}
                            </span>
                        </td>

                        <td data-label="@lang('Post Balance')" class="budget">
                           {{ showAmount($trx->post_balance) }} {{ __($general->cur_text) }}
                       </td>


                        <td data-label="@lang('Detail')">{{ __($trx->details) }}</td>
                    </tr>
                    @empty
                        <tr>
                            <td class="text-muted text-center" colspan="100%">@lang('Transaction not found')</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</section>
<!-- Transection Section Ends Here -->
@endif